from setuptools import setup

setup(
	name='frcstreamer',
	version='1.0.0',
	packages=['venv.lib.python36.site-packages.pip', 'venv.lib.python36.site-packages.pip._vendor',
			  'venv.lib.python36.site-packages.pip._vendor.idna',
			  'venv.lib.python36.site-packages.pip._vendor.pytoml',
			  'venv.lib.python36.site-packages.pip._vendor.certifi',
			  'venv.lib.python36.site-packages.pip._vendor.chardet',
			  'venv.lib.python36.site-packages.pip._vendor.chardet.cli',
			  'venv.lib.python36.site-packages.pip._vendor.distlib',
			  'venv.lib.python36.site-packages.pip._vendor.distlib._backport',
			  'venv.lib.python36.site-packages.pip._vendor.msgpack',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.util',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.contrib',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.contrib._securetransport',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.packages',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.packages.backports',
			  'venv.lib.python36.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
			  'venv.lib.python36.site-packages.pip._vendor.colorama',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib._trie',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib.filters',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib.treewalkers',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib.treeadapters',
			  'venv.lib.python36.site-packages.pip._vendor.html5lib.treebuilders',
			  'venv.lib.python36.site-packages.pip._vendor.lockfile',
			  'venv.lib.python36.site-packages.pip._vendor.progress',
			  'venv.lib.python36.site-packages.pip._vendor.requests',
			  'venv.lib.python36.site-packages.pip._vendor.packaging',
			  'venv.lib.python36.site-packages.pip._vendor.cachecontrol',
			  'venv.lib.python36.site-packages.pip._vendor.cachecontrol.caches',
			  'venv.lib.python36.site-packages.pip._vendor.webencodings',
			  'venv.lib.python36.site-packages.pip._vendor.pkg_resources',
			  'venv.lib.python36.site-packages.pip._internal', 'venv.lib.python36.site-packages.pip._internal.req',
			  'venv.lib.python36.site-packages.pip._internal.vcs',
			  'venv.lib.python36.site-packages.pip._internal.utils',
			  'venv.lib.python36.site-packages.pip._internal.models',
			  'venv.lib.python36.site-packages.pip._internal.commands',
			  'venv.lib.python36.site-packages.pip._internal.operations', 'venv.lib.python36.site-packages.idna',
			  'venv.lib.python36.site-packages.pytz', 'venv.lib.python36.site-packages.zope.interface',
			  'venv.lib.python36.site-packages.zope.interface.tests',
			  'venv.lib.python36.site-packages.zope.interface.common',
			  'venv.lib.python36.site-packages.zope.interface.common.tests', 'venv.lib.python36.site-packages.numpy',
			  'venv.lib.python36.site-packages.numpy.ma', 'venv.lib.python36.site-packages.numpy.ma.tests',
			  'venv.lib.python36.site-packages.numpy.doc', 'venv.lib.python36.site-packages.numpy.fft',
			  'venv.lib.python36.site-packages.numpy.fft.tests', 'venv.lib.python36.site-packages.numpy.lib',
			  'venv.lib.python36.site-packages.numpy.lib.tests', 'venv.lib.python36.site-packages.numpy.core',
			  'venv.lib.python36.site-packages.numpy.core.tests', 'venv.lib.python36.site-packages.numpy.f2py',
			  'venv.lib.python36.site-packages.numpy.f2py.tests', 'venv.lib.python36.site-packages.numpy.tests',
			  'venv.lib.python36.site-packages.numpy.compat', 'venv.lib.python36.site-packages.numpy.compat.tests',
			  'venv.lib.python36.site-packages.numpy.linalg', 'venv.lib.python36.site-packages.numpy.linalg.tests',
			  'venv.lib.python36.site-packages.numpy.random', 'venv.lib.python36.site-packages.numpy.random.tests',
			  'venv.lib.python36.site-packages.numpy.testing', 'venv.lib.python36.site-packages.numpy.testing.tests',
			  'venv.lib.python36.site-packages.numpy.testing._private',
			  'venv.lib.python36.site-packages.numpy.distutils',
			  'venv.lib.python36.site-packages.numpy.distutils.tests',
			  'venv.lib.python36.site-packages.numpy.distutils.command',
			  'venv.lib.python36.site-packages.numpy.distutils.fcompiler',
			  'venv.lib.python36.site-packages.numpy.matrixlib',
			  'venv.lib.python36.site-packages.numpy.matrixlib.tests',
			  'venv.lib.python36.site-packages.numpy.polynomial',
			  'venv.lib.python36.site-packages.numpy.polynomial.tests', 'venv.lib.python36.site-packages.tbapi',
			  'venv.lib.python36.site-packages.tbapi.v2', 'venv.lib.python36.site-packages.tbapi.v3',
			  'venv.lib.python36.site-packages.Crypto', 'venv.lib.python36.site-packages.Crypto.IO',
			  'venv.lib.python36.site-packages.Crypto.Hash', 'venv.lib.python36.site-packages.Crypto.Math',
			  'venv.lib.python36.site-packages.Crypto.Util', 'venv.lib.python36.site-packages.Crypto.Cipher',
			  'venv.lib.python36.site-packages.Crypto.Random', 'venv.lib.python36.site-packages.Crypto.Protocol',
			  'venv.lib.python36.site-packages.Crypto.SelfTest', 'venv.lib.python36.site-packages.Crypto.SelfTest.IO',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Hash',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Math',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Util',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Cipher',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Random',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Protocol',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.PublicKey',
			  'venv.lib.python36.site-packages.Crypto.SelfTest.Signature',
			  'venv.lib.python36.site-packages.Crypto.PublicKey', 'venv.lib.python36.site-packages.Crypto.Signature',
			  'venv.lib.python36.site-packages.iso639', 'venv.lib.python36.site-packages.certifi',
			  'venv.lib.python36.site-packages.chardet', 'venv.lib.python36.site-packages.chardet.cli',
			  'venv.lib.python36.site-packages.iso3166', 'venv.lib.python36.site-packages.isodate',
			  'venv.lib.python36.site-packages.isodate.tests', 'venv.lib.python36.site-packages.urllib3',
			  'venv.lib.python36.site-packages.urllib3.util', 'venv.lib.python36.site-packages.urllib3.contrib',
			  'venv.lib.python36.site-packages.urllib3.contrib._securetransport',
			  'venv.lib.python36.site-packages.urllib3.packages',
			  'venv.lib.python36.site-packages.urllib3.packages.backports',
			  'venv.lib.python36.site-packages.urllib3.packages.ssl_match_hostname',
			  'venv.lib.python36.site-packages.DateTime', 'venv.lib.python36.site-packages.DateTime.tests',
			  'venv.lib.python36.site-packages.requests', 'venv.lib.python36.site-packages.websocket',
			  'venv.lib.python36.site-packages.websocket.tests', 'venv.lib.python36.site-packages.setuptools',
			  'venv.lib.python36.site-packages.setuptools.extern',
			  'venv.lib.python36.site-packages.setuptools._vendor',
			  'venv.lib.python36.site-packages.setuptools._vendor.packaging',
			  'venv.lib.python36.site-packages.setuptools.command', 'venv.lib.python36.site-packages.streamlink',
			  'venv.lib.python36.site-packages.streamlink.utils', 'venv.lib.python36.site-packages.streamlink.plugin',
			  'venv.lib.python36.site-packages.streamlink.plugin.api',
			  'venv.lib.python36.site-packages.streamlink.stream',
			  'venv.lib.python36.site-packages.streamlink.plugins',
			  'venv.lib.python36.site-packages.streamlink.packages',
			  'venv.lib.python36.site-packages.streamlink.packages.flashmedia',
			  'venv.lib.python36.site-packages.SQLiteHelper', 'venv.lib.python36.site-packages.pkg_resources',
			  'venv.lib.python36.site-packages.pkg_resources.extern',
			  'venv.lib.python36.site-packages.pkg_resources._vendor',
			  'venv.lib.python36.site-packages.pkg_resources._vendor.packaging',
			  'venv.lib.python36.site-packages.streamlink_cli',
			  'venv.lib.python36.site-packages.streamlink_cli.utils', 'frcstreamer'],
	url='https://github.com/tweirtx/frcstreamer',
	license='Apache 2.0',
	author='Travis Weir',
	author_email='tweirtx@gmail.com',
	description='A package to get FRC streams'
)
